# -*- coding: utf-8 -*-
"""Automate_Muhammad_Rafi_Aditya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185If1Qyh5JlpCCIpiOZjGVYociHWyFUD
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.datasets import fetch_openml
import joblib

def automate_preprocessing():
    credit = fetch_openml('credit-g', version=1, as_frame=True)
    df = credit.frame
    X = df.drop('class', axis=1)
    y = df['class'].map({'good': 1, 'bad': 0})

    numeric_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])
    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    preprocessor = ColumnTransformer(transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    X_train_processed = preprocessor.fit_transform(X_train)
    X_test_processed = preprocessor.transform(X_test)

    joblib.dump(preprocessor, 'preprocessor.pkl')
    pd.DataFrame(X_train_processed).assign(target=y_train.values).to_csv('german_credit_train_preprocessed.csv', index=False)
    pd.DataFrame(X_test_processed).assign(target=y_test.values).to_csv('german_credit_test_preprocessed.csv', index=False)

    return X_train_processed, X_test_processed, y_train, y_test

if __name__ == "__main__":
    automate_preprocessing()
    print("Preprocessing otomatis selesai!")