name: Auto Preprocessing Advanced

on:
  push:
    paths:
      - 'preprocessing/automate_*.py'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn joblib

      - name: Run Automated Preprocessing
        working-directory: ./preprocessing
        run: python automate_muhammad_rafi_aditya.py

      - name: Upload Preprocessed Dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset-latest
          path: preprocessing/German-Credit-Dataset/
          retention-days: 90
